Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.11/x64/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.10.11/x64/lib/python3.10/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.10.11/x64/lib/python3.10/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/hostedtoolcache/Python/3.10.11/x64/lib/python3.10/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/opt/hostedtoolcache/Python/3.10.11/x64/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.10.11/x64/lib/python3.10/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.10.11/x64/lib/python3.10/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.10.11/x64/lib/python3.10/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# sets up the pynb environment
from datetime import datetime
from zoneinfo import ZoneInfo
import os
import sys

from IPython.display import HTML
import pandas as pd

from apis.dune import get_top_uniswap_proposals

module_path = os.path.abspath(os.path.join(".."))
if module_path not in sys.path:
    sys.path.append(module_path)

from stages.dataframe_filters.data_processing.statistics import (
    get_number_of_whales_to_all_voters_ratio,
    get_score_comparisons,
)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Cell [0;32mIn[1], line 10[0m
[1;32m      7[0m [38;5;28;01mfrom[39;00m [38;5;21;01mIPython[39;00m[38;5;21;01m.[39;00m[38;5;21;01mdisplay[39;00m [38;5;28;01mimport[39;00m HTML
[1;32m      8[0m [38;5;28;01mimport[39;00m [38;5;21;01mpandas[39;00m [38;5;28;01mas[39;00m [38;5;21;01mpd[39;00m
[0;32m---> 10[0m [38;5;28;01mfrom[39;00m [38;5;21;01mapis[39;00m[38;5;21;01m.[39;00m[38;5;21;01mdune[39;00m [38;5;28;01mimport[39;00m get_top_uniswap_proposals
[1;32m     12[0m module_path [38;5;241m=[39m os[38;5;241m.[39mpath[38;5;241m.[39mabspath(os[38;5;241m.[39mpath[38;5;241m.[39mjoin([38;5;124m"[39m[38;5;124m..[39m[38;5;124m"[39m))
[1;32m     13[0m [38;5;28;01mif[39;00m module_path [38;5;129;01mnot[39;00m [38;5;129;01min[39;00m sys[38;5;241m.[39mpath:

File [0;32m~/work/gov_analysis/gov_analysis/book/apis/dune.py:4[0m
[1;32m      1[0m [38;5;28;01mfrom[39;00m [38;5;21;01mos[39;00m [38;5;28;01mimport[39;00m getenv
[1;32m      3[0m [38;5;28;01mfrom[39;00m [38;5;21;01mdotenv[39;00m [38;5;28;01mimport[39;00m load_dotenv
[0;32m----> 4[0m [38;5;28;01mfrom[39;00m [38;5;21;01mhttpx[39;00m [38;5;28;01mimport[39;00m Client, Timeout
[1;32m      7[0m load_dotenv()
[1;32m      9[0m DUNE_API [38;5;241m=[39m getenv([38;5;124m"[39m[38;5;124mDUNE_API[39m[38;5;124m"[39m)

[0;31mModuleNotFoundError[0m: No module named 'httpx'
ModuleNotFoundError: No module named 'httpx'

